# Generated by Django 4.2.7 on 2023-11-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
