# Generated by Django 4.2.7 on 2023-11-26 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='item',
            new_name='post',
        ),
    ]
