# Generated by Django 4.2.7 on 2023-11-27 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_alter_comment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='item',
        ),
    ]
