# Generated by Django 4.2.7 on 2023-11-28 18:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_rename_post_comment_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
