# Generated by Django 4.2.7 on 2023-11-30 09:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_alter_item_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
