# Generated by Django 4.2.7 on 2023-12-03 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='users',
        ),
    ]
