# Generated by Django 4.2.7 on 2023-12-03 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_rename_user_customer_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
