# Generated by Django 4.2.7 on 2023-12-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0020_alter_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(max_length=255),
        ),
    ]
