# Generated by Django 4.2.7 on 2023-12-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0021_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
