# Generated by Django 4.2.7 on 2023-12-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0025_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='file',
            field=models.FileField(blank=True, upload_to='item_files'),
        ),
    ]
