# Generated by Django 4.2.7 on 2024-01-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0026_item_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='video',
            field=models.FileField(blank=True, upload_to='item_videos'),
        ),
    ]
