# Generated by Django 4.2.7 on 2023-12-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_todo_name_todo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255, null=True)),
                ('comment', models.TextField(max_length=500, null=True)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
