# Generated by Django 4.2.7 on 2023-12-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_messages_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('iconClass', models.CharField(max_length=255, null=True)),
                ('content', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
