# Generated by Django 4.2.7 on 2023-12-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contactlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactlist',
            name='iconClass',
        ),
        migrations.AddField(
            model_name='contactlist',
            name='icon',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
