# Generated by Django 4.2.7 on 2023-12-14 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_contactlist_iconclass_contactlist_icon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactList',
            new_name='ContactInfo',
        ),
    ]
