# Generated by Django 4.2.7 on 2023-12-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_contactlist_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('icon', models.TextField(max_length=255, null=True)),
                ('content', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
