# Generated by Django 4.2.7 on 2023-12-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_aboutinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
