# Generated by Django 4.2.7 on 2023-12-29 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserVisit',
        ),
    ]
