# Generated by Django 4.2.7 on 2023-12-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_user_uservisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservisit',
            name='date',
            field=models.DateTimeField(default=None),
        ),
    ]
