# Generated by Django 4.2.7 on 2023-12-29 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_uservisit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservisit',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
