# Generated by Django 4.2.7 on 2024-01-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_uservisit_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField(max_length=1000)),
            ],
        ),
    ]
