# Generated by Django 4.2.7 on 2024-01-02 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_homehero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeHero',
        ),
    ]
