# Generated by Django 4.2.7 on 2024-01-04 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_terms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terms',
            options={'ordering': ('title',), 'verbose_name_plural': 'Terms'},
        ),
    ]
