# Generated by Django 4.2.7 on 2023-12-27 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_events_end_date_events_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ('title',), 'verbose_name_plural': 'Events'},
        ),
    ]
