# Generated by Django 4.2.7 on 2023-12-31 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_messages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ('title',), 'verbose_name_plural': 'Messages'},
        ),
        migrations.AddField(
            model_name='messages',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
