# Generated by Django 4.2.7 on 2023-12-31 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_messages_options_messages_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
