# Generated by Django 4.2.7 on 2023-12-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_messages_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ('title',)},
        ),
        migrations.AlterField(
            model_name='messages',
            name='status',
            field=models.BooleanField(default=False, help_text='Read'),
        ),
    ]
