# Generated by Django 4.2.7 on 2024-01-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_rename_messages_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='badge',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
